# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- trunk

pool:
  vmImage: ubuntu-latest
  
schedules:
- cron: "*/2 * * * *"
  displayName: daily build
  branches:
    include:
    - main

jobs:
- deployment: deploy
  environment: validation
  strategy:
   runOnce:
     deploy:
       steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

